name: Read MD Files
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  readFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install front-matter
        run: npm install front-matter

      - name: Install axios
        run: npm install axios

      - name: Get Added Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: List all added files
        run: |
          mapfile -d ',' -t added_files < <(printf '%s,' '${{ steps.files.outputs.added }}')
          for added_file in "${added_files[@]}"; do
            echo "Do something with this ${added_file}."
            body=$(cat "${added_file}")
            body_json=$(printf '%s' "${body}" | sed 's/"/\\"/g' | jq -Rs '.' | tr -d '\n')
            title=$(node -e "const fs = require('fs'); const fm = require('front-matter'); const content = fs.readFileSync('${added_file}', 'utf8'); const parsed = fm(content); console.log(parsed.attributes.title);")
            labels=$(node -e "const fs = require('fs'); const fm = require('front-matter'); const content = fs.readFileSync('${added_file}', 'utf8'); const parsed = fm(content); console.log(parsed.attributes.labels);")
            echo "title: ${title}, body: ${body_json}, labels: ${labels}."
            echo "Sending POST request..."
            response=$(node -e "const axios = require('axios'); axios.post('https://api.github.com/repos/oicoder/blog/issues', {
              title: '${title}',
              assignees: [
                'oicoder'
              ],
              body: ${body_json},
              labels: ${labels}
            }, {
              headers: {
                'Accept': 'application/vnd.github.v3+json',
                'Authorization': 'Bearer ${{ secrets.ACCESS_TOKEN }}',
                'X-GitHub-Api-Version': '2022-11-28'
              }
            }).then(res => {
              console.log(res.data);
            })
            .catch(err => {
              console.log(err);
            })")
            echo "Response: ${response}"
          done
