name: Read MD Files
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  readFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Added Files
        id: added-files
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all added files
        run: |
          for file in ${{ steps.added-files.outputs.deleted }}; do
            echo "$file was deleted"
            echo "${HOME}/files_deleted.json"
          done
