name: Add Issue
on:
  push:
    branches:
      - main
    paths:
      - 'blog/**/*.md'

jobs:
  addIssue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Read and process MD file
      id: process_md
      run: |
        # Read file content
        FILE_PATHS=$(find blog -name '*.md')
        
        for FILE_PATH in $FILE_PATHS; do
          FILE_CONTENT=$(cat $FILE_PATH)
          
          # Extract labels, milestone, and title from front-matter
          LABELS=$(echo "$FILE_CONTENT" | grep -oP '(?<=labels:\s)\S+')
          MILESTONE=$(echo "$FILE_CONTENT" | grep -oP '(?<=milestone:\s)\S+')
          TITLE=$(echo "$FILE_CONTENT" | grep -oP '(?<=title:\s)\S+')
          
          # Extract content below front-matter as issue content
          ISSUE_CONTENT=$(echo "$FILE_CONTENT" | awk '/---/{n++} n==2')

          # Create issue using the extracted information
          # Replace the following line with your own code to create the issue
          echo "Creating issue for file: $FILE_PATH"
          echo "Labels: $LABELS"
          echo "Milestone: $MILESTONE"
          echo "Title: $TITLE"
          echo "Issue Content: $ISSUE_CONTENT"
        done
