name: Read MD Files
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  readFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install front-matter
        run: npm install front-matter

      - name: Install axios
        run: npm install axios

      - name: Get Added Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: List all added files
        run: |
          mapfile -d ',' -t added_files < <(printf '%s,' '${{ steps.files.outputs.added }}')
          for added_file in "${added_files[@]}"; do
            echo "Do something with this ${added_file}."
            body=$(node -e "const fs = require('fs'); const content = fs.readFileSync('${added_file}', 'utf8'); console.log(JSON.stringify(content));")
            title=$(node -e "const fs = require('fs'); const fm = require('front-matter'); const content = fs.readFileSync('${added_file}', 'utf8'); const parsed = fm(content); console.log(parsed.attributes.title);")
            labels=$(node -e "const fs = require('fs'); const fm = require('front-matter'); const content = fs.readFileSync('${added_file}', 'utf8'); const parsed = fm(content); console.log(parsed.attributes.labels);")
            milestone=$(node -e "const fs = require('fs'); const fm = require('front-matter'); const content = fs.readFileSync('${added_file}', 'utf8'); const parsed = fm(content); console.log(parsed.attributes.milestone);")
            echo "${body}, title: ${title}, labels: ${labels}, milestone: ${milestone}."
            echo "Sending POST request..."
            
            echo "Response: "
          done
