name: Read MD Files
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  readFiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Read MD files
      id: read_md_files
      run: |
        # Find all added or modified files
        CHANGED_FILES=$(git diff --name-only --diff-filter=AM origin/main...HEAD)

        # Filter Markdown files
        MD_FILES=$(echo "$CHANGED_FILES" | grep -E '\.md$')

        # Process each Markdown file
        for FILE_PATH in $MD_FILES; do
          # Read file content
          FILE_CONTENT=$(cat $FILE_PATH)

          # Extract information from the content as needed
          # Replace the following lines with your own code to process the file
          echo "Processing file: $FILE_PATH"
          echo "File content: $FILE_CONTENT"
        done
        