name: Add Issue
on:
  push:
    branches:
      - main

jobs:
  addIssue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Read and process MD file
      id: process_md
      run: |
        # Read file content
        FILE_CONTENT=$(cat ${{ github.event.inputs.filePath }})
        
        # Extract labels, milestone, and title from front-matter
        LABELS=$(echo "$FILE_CONTENT" | grep -oP '(?<=labels:\s)\S+')
        MILESTONE=$(echo "$FILE_CONTENT" | grep -oP '(?<=milestone:\s)\S+')
        TITLE=$(echo "$FILE_CONTENT" | grep -oP '(?<=title:\s)\S+')
        
        # Extract content below front-matter as issue content
        ISSUE_CONTENT=$(echo "$FILE_CONTENT" | awk '/---/{n++} n==2')

        # Set output variables
        echo "::set-output name=labels::$LABELS"
        echo "::set-output name=milestone::$MILESTONE"
        echo "::set-output name=title::$TITLE"
        echo "::set-output name=issue_content::$ISSUE_CONTENT"

    - name: Create Issue
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { context, github } = require('@actions/github');
          const { title, body, labels, milestone } = context.payload.inputs;
          
          github.issues.create({
            ...context.repo,
            title,
            body,
            labels: labels.split(','),
            milestone
          });
