name: Read MD Files
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '**/*.md'

jobs:
  readFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Added Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: List all added files
        run: |
          mapfile -d ',' -t added_files < <(printf '%s,' '${{ steps.files.outputs.added }}')
          for added_file in "${added_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
